---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-processor-service.fullname" . }}
  namespace: "{{ .Release.Namespace }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cluster-processor-service.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cluster-processor-service.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-processor-service.fullname" . }}
    namespace: "{{ .Release.Namespace }}"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cluster-processor-service.fullname" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
  - nonResourceURLs:
      - '*'
    verbs:
      - '*'
